# Generated by Django 5.0.1 on 2024-03-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_column_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Note',
        ),
    ]
