# Generated by Django 5.0.3 on 2024-03-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_rename_object_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.IntegerField(),
        ),
    ]
