# Generated by Django 5.0.3 on 2024-03-19 12:44

from django.db import migrations, models
from kanban.models import Note


def set_default_value(apps, schema_editor):
    for obj in Note.objects.all():
        obj.position = obj.id
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_column_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_value)
    ]
