# Generated by Django 5.0.3 on 2024-05-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_column_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='kanban.person'),
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Team',
        ),
    ]
